name: reviewdog

on:
  workflow_dispatch:

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.CHECKSTYLE_TOKEN }}
          reporter: github-pr-review
          level: warning
